<?php
const MC_PAGE_PROFILE = "profile";
const MC_PAGE_REGISTER = "register";
const CFT_DIRECTORY = "cft";
const MC_ABSTRACT = "abstract";
const MC_BIRTHDAY = "birthday";
const MC_PHONE = "phone";
const MC_DNI = "DNI";
const MC_EMAIL = "email";
const MC_POLICY_1 = "mc-policy-1";
const MC_POLICY_2 = "mc-policy-2";
const MC_POLICY_3 = "mc-policy-3";
const MC_CFT_WHEN_WHERE = 'cft_when_and_where';
const MC_PROFESSION = 'profession';
const MC_PROFESSION_OPTIONS = "mc_professions_options";
const MC_MODE = 'mode';
const MC_METABOX_IMAGE = "image";
const MC_METABOX_PERMISSION = "permission";
const MC_COUNTRY = "country";
const MC_METABOX_GENDER = "gender";
const MC_WEBSITE = "website";
const MC_WEBSITE_MODE = "website_mode";
const MC_LINK_WEBSITE = 'website';
const MC_LINK_FACEBOOK = 'facebook';
const MC_LINK_LINKEDIN = 'linkedin';
const MC_LINK_INSTAGRAM = 'instagram';
const MC_LINK_TWITTER = 'twitter';
const MC_WORKS_WITH = "works_with";
const MC_GENDER = "gender";
const MC_PICTURE = "picture";
const MC_PASSWORD_1 = "password_1";
const MC_PASSWORD_2 = "password_2";
const MC_AVATAR_URL = "avatar_url";
const MC_AVATAR_ID = "avatar_url_id";
const MC_METABOX_PERMISSION_RULE = "permission_rule";
const MC_PERSON = 'person';
const MC_CFT = 'cft';
const MC_USER_DETAILS = 'mc-user-details';
const MC_USER_REF = 'entity_ref';
const MC_ENABLED = 'enabled';
const MC_KIND = 'kind';
const MC_SETTING = "settings";
const MC_CITY = "city";
const MC_POST_BIND = 'post_bind';

const MC_LOGGED_REQUIRED = "logged_required";
const MC_CAPABILITIES = "capabilities";
const MC_NAME = "name";
const MC_ID = "id";
const MC_POST_TYPES = "post_types";
const MC_PERMISSIONS = 'permissions';

const MC_DEFAULT_PERMISSION = [
    MC_NAME => "New item",
    MC_LOGGED_REQUIRED => true,
    MC_POST_TYPES => [],
    MC_CAPABILITIES => []
];
